### ISSUE TITLE
Browser Compatabiliy / can't log in

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#251] opened 2020-03-25 15:32 UTC
**Describe the bug**
A clear and concise description of the problem and bug effects.

**Environment information:**

- OS: **[EndeavourOS](https://github.com/endeavouros-team) (Arch Linux)**
- Platform: **Linux 5.5.11-arch1-1 x86_64**
- Affected Browsers: **waterfox-current-bin Version 2020.03**
          **vivaldi-stable Version 80.0.3987.158 (Official Build) (64-bit)**
          freshly intalled **firefox Version 74.0 (with no addons)**

**Steps to Reproduce**

In skywire-mainnet repo on develop:
1. make build; make install
2. skywire-cli visor gen-config -rt
3. hypervisor gen-config -rt 
4. Paste the hyperisor pub key into the visor config according to the sample here https://github.com/SkycoinProject/skywire-mainnet#hypervisor-setup
5. skywire-visor
6. hypervisor 
7. go to localhost:8080
8. attempt login 

**Actual behavior**

The UI is present at localhost:8080 in the browser after modifying the configuration files and starting the visor and hypervisor processes. However; it will not let me log in. I am able to set the password correctly and recieve the green confirmaion of the password being set at the top of the window, but entering the set password has no effect after that point. The password is not erased, no dialog about incorrect password is displayed.

**Expected behavior**

Login Success

**Additional context**

Will update this issue as I test with other browsers

**Possible implementation**
```
‾\_(ツ)_/‾
```

**Comment by Senyoret1** [comment] 2020-03-25 16:34
@0pcom That should have been solved by https://github.com/SkycoinProject/skywire-mainnet/pull/243 . Could you please check if the changes made on that PR are already on your local branch?

**Comment by jdknives** [comment] 2020-03-25 16:52
He said he was already on the latest change from `develop` branch. So this would have been included. @Senyoret1

**Comment by Senyoret1** [comment] 2020-03-25 20:00
Ok, I was not able to reproduce the problem at first, so I checked several of things to try to get posible causes. The first thing I found out was that when using `hypervisor gen-config -rt` the generated sonfiguration file had `"enable_auth": false,`, so the login page should not be visible, the manager is configured to skip it in that case.

After changing `enable_auth` to true, the loging page should work well, because the default configuration has `cookies.secure` set to false. The problem described on this issue happens when the cookie is secure and the connection is made using http, because browsers don't send secure cookies via http, so all operations fail and that makes the manager return to the login page. It is important to check if the hypervisor configuration file has `enable_tls` set to false and the value of `cookies.secure` is also false. If `cookies.secure` is true, that is the cause of the problem.

In fact, I had several inconsistent results while testing, but at the end everything was working as expected, so I can no totally discard the possibility of the problem being somewhere else, but I think the hypervisor configuration file is the best place to start investigating, specially taking into account that the default configuration was changed just a day ago.

**Comment by 0pcom** [comment] 2020-03-25 22:54
I repeated the steps and I'm able to access the manager UI on localhost (with waterfox). I wasn't prompted for a password.

When I click on the visor's key, I get the following error
![Screenshot_2020-03-25_17-55-36](https://user-images.githubusercontent.com/36607567/77593339-0aac5b80-6ec2-11ea-9071-303fcd3e9700.png)

**Comment by evanlinjin** [comment] 2020-03-25 23:16
@0pcom
1. Can you confirm whether it works in a more common browser (such as Firefox/Chrome).
2. If not, can you toggle developer tools and provide us with the network analysis. Also, logs from `skywire-visor` and `hypervisor` will be very helpful.

**Comment by 0pcom** [comment] 2020-03-26 13:32
Somehow, when I repeated the same steps again (just now on a different machine; freshly cloning the develop branch) it seems to have worked. No errors so far at least. Still using waterfox at this point.

I'm not sure if there was some commit since yesterday or what I might have one differently but it should become clear when I try again later from the main computer.

![Screenshot_2020-03-26_08-26-08](https://user-images.githubusercontent.com/36607567/77652414-2bb19280-6f3c-11ea-8600-8d01d19dc4d5.png)

**Comment by evanlinjin** [comment] 2020-03-27 01:38
@0pcom Thank you for your input. However, in the future, it will be helpful and also a time-saver to provide more useful details (as stated in https://github.com/SkycoinProject/skywire-mainnet/issues/251#issuecomment-604137965).

**Comment by jdknives** [comment] 2020-03-30 17:09
I will close this for now. If it pops up again, we can reopen. @0pcom @evanlinjin

**Closed as completed by jdknives** 2020-03-30 17:09 UTC
Labels: bug
