### ISSUE TITLE
Systray app inhibits binary portability

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1185] opened 2022-05-10 14:16 UTC
The systray app seems to introduce another runtime dependency (besides glibc). It is not obvious what this dependency is.

This issue is apparent in the skywire-dev debian package available from the [apt repo](http://deb.skywire.skycoin.com) (which can also be downloaded directly from the [archive](http://deb.skywire.skycoin.com/archive) )

The skywire-dev .deb package contains binaries which were statically compiled with musl on archlinux for testing the systray integration with the packages.

When the package is installed, the autoconfig script fails to execute correctly. When the binaries are manually executed, a very generic error is produced; `bash - no such file`

But the binaries do in fact exist, and are provided by the package.

(#1180 is a testing workaround / hotfix for this issue, but does not address the root cause.)

Research indicates this behavior is evidence of an absent runtime dependency.

This does not happen with binaries statically compiled from the 0.6.0 source archive. Which strongly suggests that the systray is the culprit.

Furthermore, it does not matter if the binaries are compiled with or without the systray tag, the portability issue remains regardless.

When the binaries are not statically compiled, an error regarding incompatible or not present glibc is produced (as expected)

The systray app is only needed for desktop installations of skywire; **it would be best for the systray app to be its own binary**, and packaged separately from the rest of skywire.

Additionally, I suggest that the systray be included in a separate binary release archive / not included in the same binary release archive as the visor, cli, and app binaries because it does not represent core functionality, only an extension for desktop integration. Also, the system (linux distribution) on which the linux binaries were compiled should be included in the release notes

In conclusion, the following changes are requested:

* **Make the systray app a separate binary from the visor**
* **create all the functionalities of the systray buttons / menu items directly in skywire-cli** (or skywire-visor if / where appropriate)
* **The systray app should calls these commands directly when the buttons are clicked**, which will greatly simplify the implementation and make testing the systray functions without running the systray itself much easier.
* **The systray app will depend on the skywire-cli & visor binaries existing in the executable PATH**

The following additional functionality will be made possible by these changes:

* **config generation and updating**
* **stopping *and starting* the visor** (via systemd, on linux, or by calling a script to avoid hardcoding the systemd service name)

**Comment by jdknives** [comment] 2022-05-27 12:20
Duplicate of #1140

**Closed as completed by jdknives** 2022-05-27 12:20 UTC
